/**
 * Invoice PDF via @react-pdf/renderer.
 * Company branding + salary summary line items.
 */

import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  Image,
  StyleSheet,
  renderToBuffer,
  Font,
} from "@react-pdf/renderer";
import { getInterBold, getInterRegular } from "@/lib/linkedin/fonts";
import { readFileSync } from "fs";
import { join } from "path";

let logoBase64: string | null = null;
try {
  const logoPath = join(process.cwd(), "public", "images", "mindvista-official-logo-light.png");
  const logoBuffer = readFileSync(logoPath);
  logoBase64 = `data:image/png;base64,${logoBuffer.toString("base64")}`;
} catch (e) {
  console.error("Failed to read invoice logo:", e);
}

Font.register({
  family: "Inter",
  fonts: [
    { src: `data:font/woff;base64,${getInterRegular().toString("base64")}`, fontWeight: 400 },
    { src: `data:font/woff;base64,${getInterBold().toString("base64")}`, fontWeight: 700 },
  ],
});

const styles = StyleSheet.create({
  page: { padding: 50, fontFamily: "Inter", fontSize: 10, color: "#0f172a" },
  header: { marginBottom: 30, borderBottomWidth: 1, borderBottomColor: "#e2e8f0", paddingBottom: 20 },
  company: { fontSize: 20, fontWeight: 700, color: "#1e293b", marginBottom: 4 },
  address: { fontSize: 9, color: "#64748b", marginBottom: 4 },
  title: { fontSize: 14, fontWeight: 600, color: "#334155", marginTop: 10 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 11, fontWeight: 600, color: "#334155", marginBottom: 8, textTransform: "uppercase", letterSpacing: "0.5px" },
  tableHeader: { flexDirection: "row", backgroundColor: "#f1f5f9", padding: 8, marginBottom: 4 },
  tableRow: { flexDirection: "row", padding: 6, borderBottomWidth: 1, borderBottomColor: "#e2e8f0" },
  colDesc: { width: "60%" },
  colAmt: { width: "40%", textAlign: "right" },
  total: { marginTop: 20, paddingTop: 12, borderTopWidth: 1, borderTopColor: "#cbd5e1" },
  footer: { position: "absolute", bottom: 40, left: 50, right: 50, fontSize: 8, color: "#94a3b8" },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 4 },
});

export type InvoiceData = {
  companyName: string;
  companyAddress?: string | null;
  employeeName: string;
  designation: string;
  periodLabel: string;
  payDate: string;
  currency: string;
  lineItems: { description: string; amount: number }[];
  total: number;
  footer?: string | null;
};

function InvoiceDoc({ data }: { data: InvoiceData }) {
  const fmt = (n: number) =>
    `${data.currency} ${n.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          {logoBase64 ? (
            <Image src={logoBase64} style={{ width: 140, marginBottom: 8 }} />
          ) : (
            <Text style={styles.company}>{data.companyName}</Text>
          )}
          {data.companyAddress ? (
            <Text style={styles.address}>{data.companyAddress}</Text>
          ) : null}
          <Text style={styles.title}>Invoice — {data.periodLabel}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Employee</Text>
          <View style={styles.row}>
            <Text>Name: {data.employeeName}</Text>
            <Text>Designation: {data.designation}</Text>
          </View>
          <View style={styles.row}>
            <Text>Period: {data.periodLabel}</Text>
            <Text>Pay Date: {data.payDate}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Salary Summary</Text>
          <View style={styles.tableHeader}>
            <Text style={styles.colDesc}>Description</Text>
            <Text style={styles.colAmt}>Amount</Text>
          </View>
          {data.lineItems.map((item, i) => (
            <View key={i} style={styles.tableRow}>
              <Text style={styles.colDesc}>{item.description}</Text>
              <Text style={styles.colAmt}>{fmt(item.amount)}</Text>
            </View>
          ))}
        </View>

        <View style={styles.total}>
          <View style={styles.row}>
            <Text style={{ fontWeight: 700, fontSize: 12, marginRight: 20 }}>Total</Text>
            <Text style={{ fontWeight: 700, fontSize: 12 }}>{fmt(data.total)}</Text>
          </View>
        </View>

        <Text style={styles.footer}>
          {data.footer ||
            "Confidential — generated by MindVista HRMS. This document is for employee compensation purposes only."}
        </Text>
      </Page>
    </Document>
  );
}

export async function renderInvoicePdf(data: InvoiceData): Promise<Buffer> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-enums
  const element = React.createElement(InvoiceDoc as any, { data }) as any;
  return Buffer.from(await renderToBuffer(element));
}