/**
 * Salary slip PDF via @react-pdf/renderer (same stack as LinkedIn reports).
 */

import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
  renderToBuffer,
} from "@react-pdf/renderer";
import { getInterBold, getInterRegular } from "@/lib/linkedin/fonts";

Font.register({
  family: "Inter",
  fonts: [
    { src: `data:font/woff;base64,${getInterRegular().toString("base64")}`, fontWeight: 400 },
    { src: `data:font/woff;base64,${getInterBold().toString("base64")}`, fontWeight: 700 },
  ],
});

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Inter", fontSize: 10, color: "#0f172a" },
  header: { marginBottom: 20, borderBottomWidth: 1, borderBottomColor: "#e2e8f0", paddingBottom: 12 },
  company: { fontSize: 16, fontWeight: 700, color: "#0f172a" },
  title: { fontSize: 12, color: "#64748b", marginTop: 4 },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 4 },
  section: { marginTop: 16 },
  sectionTitle: { fontSize: 11, fontWeight: 700, marginBottom: 8, color: "#334155" },
  tableHeader: { flexDirection: "row", backgroundColor: "#f1f5f9", padding: 6 },
  tableRow: { flexDirection: "row", padding: 6, borderBottomWidth: 1, borderBottomColor: "#f1f5f9" },
  colDesc: { width: "70%" },
  colAmt: { width: "30%", textAlign: "right" },
  total: { marginTop: 12, paddingTop: 8, borderTopWidth: 1, borderTopColor: "#cbd5e1" },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, fontSize: 8, color: "#94a3b8" },
});

export type SalarySlipData = {
  companyName: string;
  companyAddress?: string | null;
  footer?: string | null;
  employeeName: string;
  employeeCode: string | null;
  designation: string;
  periodLabel: string;
  payDate: string;
  currency: string;
  earnings: { description: string; amount: number }[];
  deductions: { description: string; amount: number }[];
  netPay: number;
};

function SlipDoc({ data }: { data: SalarySlipData }) {
  const fmt = (n: number) =>
    `${data.currency} ${n.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.company}>{data.companyName}</Text>
          {data.companyAddress ? <Text style={styles.title}>{data.companyAddress}</Text> : null}
          <Text style={styles.title}>Salary Slip — {data.periodLabel}</Text>
        </View>

        <View style={styles.section}>
          <View style={styles.row}>
            <Text>Employee: {data.employeeName}</Text>
            <Text>Pay date: {data.payDate}</Text>
          </View>
          <View style={styles.row}>
            <Text>ID: {data.employeeCode || "—"}</Text>
            <Text>Designation: {data.designation}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Earnings</Text>
          <View style={styles.tableHeader}>
            <Text style={styles.colDesc}>Description</Text>
            <Text style={styles.colAmt}>Amount</Text>
          </View>
          {data.earnings.map((e, i) => (
            <View key={i} style={styles.tableRow}>
              <Text style={styles.colDesc}>{e.description}</Text>
              <Text style={styles.colAmt}>{fmt(e.amount)}</Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Deductions</Text>
          <View style={styles.tableHeader}>
            <Text style={styles.colDesc}>Description</Text>
            <Text style={styles.colAmt}>Amount</Text>
          </View>
          {data.deductions.length === 0 ? (
            <View style={styles.tableRow}>
              <Text style={styles.colDesc}>None</Text>
              <Text style={styles.colAmt}>{fmt(0)}</Text>
            </View>
          ) : (
            data.deductions.map((d, i) => (
              <View key={i} style={styles.tableRow}>
                <Text style={styles.colDesc}>{d.description}</Text>
                <Text style={styles.colAmt}>{fmt(d.amount)}</Text>
              </View>
            ))
          )}
        </View>

        <View style={styles.total}>
          <View style={styles.row}>
            <Text style={{ fontWeight: 700, fontSize: 12 }}>Net Salary</Text>
            <Text style={{ fontWeight: 700, fontSize: 12 }}>{fmt(data.netPay)}</Text>
          </View>
        </View>

        <Text style={styles.footer}>
          {data.footer || "Confidential — generated by MindVista HRMS. This document is for the named employee only."}
        </Text>
      </Page>
    </Document>
  );
}

export async function renderSalarySlipPdf(data: SalarySlipData): Promise<Buffer> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const element = React.createElement(SlipDoc as any, { data }) as any;
  return Buffer.from(await renderToBuffer(element));
}
